### ISSUE TITLE
大佬可否抽空更新一下

### ISSUE THREAD

**Issue by serosme** [xzsk2/TG-EFB-QQ-Docker#10]
Go-CQHTTP已经更新到v1.0.0-beta7-fix2，修复了图片上传的问题，求大佬更新一下

**Comment by serosme** [comment]
现在版本提示v1.0.0-beta7-fix1，EFB-QQ-Slave也提示更新2.0.1

**Comment by sakarie9** [comment]
go-cqhttp已经是fix2了，重新拉取一下镜像就行，可以用watchtower更
```
docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower -c \
    --run-once \
    gocq
```

qq-slave提示要更新但其实也已经是最新了，无视即可
