### ISSUE TITLE
EFB-QQ-Slave有更新啦

### ISSUE THREAD

**Issue by qi-mooo** [xzsk2/TG-EFB-QQ-Docker#11]
🐧💻 CoolQ Alert, System:
New version(2.0.1) of EFB-QQ-Slave has released! Please manually update EQS by stopping ehForwarderbot first and then execute <code>pip3 install --upgrade efb-qq-slave</code>

**Comment by sakarie9** [comment]
已经是最新了，EFB-QQ-Slave 换了正式版的以后应该不会提示 2.0.1 更新了😀
