### ISSUE TITLE
无法生成config.json文件

### ISSUE THREAD

**Issue by ossima-ze** [xzsk2/TG-EFB-QQ-Docker#15]
在配置好 blueset.telegram中的token以及admin，与gocp中的account: ui之后运行

```bash
sudo docker run --rm -it --name="gocq" -v $PWD/gocq:/data xzsk2/gocqhttp-docker:latest
```

并按照要求，我选择了http通信协议：

![image](https://user-images.githubusercontent.com/48322394/143997759-99fa90f3-aec2-4c5c-8353-d1f66e584a4e.png)

但是并没有生成config.json文件

![image](https://user-images.githubusercontent.com/48322394/143998090-f0681d94-586c-4475-92a3-cab330aa086c.png)

在接下来执行 `docker-compose up -d` 遇到了循环要求选择通信协议的问题，无法实现登陆，如下：

![image](https://user-images.githubusercontent.com/48322394/143998348-fed56c8e-bcf9-49ad-8d85-541647a8fb4c.png)

**Comment by sakarie9** [comment]
检查一下运行目录？目录正确的话是不会提示未找到配置文件的

```
sudo docker run --rm -it --name="gocq" -v $PWD/gocq:/data xzsk2/gocqhttp-docker:latest
```

这条命令应该在与`docker-compose.yml`同级的目录下运行，在你那里就是在`EFB-QQ-SLAVE`下面运行

**Comment by ossima-ze** [comment]
> 检查一下运行目录？目录正确的话是不会提示未找到配置文件的
> 
> ```
> sudo docker run --rm -it --name="gocq" -v $PWD/gocq:/data xzsk2/gocqhttp-docker:latest
> ```
> 
> 这条命令应该在与`docker-compose.yml`同级的目录下运行，在你那里就是在`EFB-QQ-SLAVE`下面运行

我重新在本地WSL2运行一次能生成 `config.json` 以及相关用户数据，然后SCP到服务器就能运行了，有够神奇的说 awa？
