### ISSUE TITLE
TG 收到图片 gif 和好友申请消息会重复3、4次

### ISSUE THREAD

**Issue by gaxdel** [xzsk2/TG-EFB-QQ-Docker#18]
TG 收到图片 gif 和好友申请消息会重复3、4次。

**Comment by sakarie9** [comment]
大概是网络问题，`docker logs efb` `docker logs gocq` 看看重复时有没有什么错误日志

配置文件里适当增加timeout

**Comment by gaxdel** [comment]
增加timeout后解决了，谢谢。
