### ISSUE TITLE
想问下机器人的command

### ISSUE THREAD

**Issue by qinfengge** [xzsk2/TG-EFB-QQ-Docker#2]
搭建完成后接收消息没什么问题,就是第一次用这玩意,不太清楚TG机器人的command,以及怎么发送消息.
希望大佬指点下迷津,感激不尽.

**Comment by sakarie9** [comment]
[efb-telegram-master](https://github.com/ehForwarderBot/efb-telegram-master/blob/master/readme_translations/zh_CN.rst) 的文档里有详细说明

**Comment by qinfengge** [comment]
> [efb-telegram-master](https://github.com/ehForwarderBot/efb-telegram-master/blob/master/readme_translations/zh_CN.rst) 的文档里有详细说明

了解了,但是我的问题是EFB启动失败...
