### ISSUE TITLE
如何取消群消息的通知呢？

### ISSUE THREAD

**Issue by yuhuan9971** [xzsk2/TG-EFB-QQ-Docker#22]
抱歉我没找到取消群通知的方法，我有一个群很热闹开了接收消息但不提醒，只要群里有消息Bot就会一直响

**Comment by sakarie9** [comment]
tg里暂停消息通知-永久静音就不弹通知了

**Comment by yuhuan9971** [comment]
那这样子不是也收不到私人消息了嘛🤔> tg里暂停消息通知-永久静音就不弹通知了

**Comment by sakarie9** [comment]
那就单独建一个tg群，然后给bot发/link把那个qq群链接到tg群然后静音群

**Comment by yuhuan9971** [comment]
> 那就单独建一个tg群，然后给bot发/link把那个qq群链接到tg群然后静音群

学到了，谢谢你
