### ISSUE TITLE
为什么停止后自动更新无效

### ISSUE THREAD

**Issue by Allroha** [xzsk2/TG-EFB-QQ-Docker#28]
04:03:41->pwd
/root/TG-EFB-QQ-Docker
[root@CloudCone]
05:35:36->docker-compose down
Stopping efb  ... done
Stopping gocq ... done
Removing efb  ... done
Removing gocq ... done
[root@CloudCone]
05:36:10->
>     docker run -d \
>     --name watchtower \
>     --restart unless-stopped \
>     -v /var/run/docker.sock:/var/run/docker.sock \
>     containrrr/watchtower -c \
>     --interval 3600 \
>     efb gocq
802b8fba3c7e6ab02f4cceee7b7d1239068c06857614e1e3b3ed6dd386b4db54
[root@CloudCone]
05:36:14->pip3 install --upgrade efb-qq-slave
Requirement already satisfied: efb-qq-slave in /usr/local/lib/python3.8/dist-packages (2.0.1)
xxxx
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

还是提示
New version(2.0.1) of EFB-QQ-Slave has released! Please manually update EQS by stopping ehForwarderbot first and then execute <code>pip3 install --upgrade efb-qq-slave</code>

**Comment by sakarie9** [comment]
watchtower会自动更新运行的容器所以不需要手动down

然后下面那个EFB-QQ-Slave的不用管，镜像里用的是git的最新版，比提示的2.0.1要新

**Comment by Allroha** [comment]
> watchtower会自动更新运行的容器所以不需要手动down
> 
> 然后下面那个EFB-QQ-Slave的不用管，镜像里用的是git的最新版，比提示的2.0.1要新

谢谢！
