### ISSUE TITLE
tgbot可以接收消息但发送指令无效

### ISSUE THREAD

**Issue by StephenSSR** [xzsk2/TG-EFB-QQ-Docker#3]
请问为什么我搭建好后可以接收消息，但向tg机器人发送指令无效，导致不能分组和发送消息。

**Comment by sakarie9** [comment]
检查`/blueset.telegram/config.yaml`下的`admins`是否是自己的`Telegram ID`？

**Comment by StephenSSR** [comment]
id没有问题

**Comment by sakarie9** [comment]
似乎和 #4 一样的问题，试试 https://github.com/xzsk2/TG-EFB-QQ-Docker/issues/4#issuecomment-877947769

**Comment by sakarie9** [comment]
根据 https://github.com/xzsk2/TG-EFB-QQ-Docker/issues/4#issuecomment-878283090 的方法

在 `efb/profiles/default/config.yaml` 中屏蔽掉中间件 `xzsk2.filter` 即可解决此问题
