### ISSUE TITLE
报错 : exec /bin/sh: exec format error 

### ISSUE THREAD

**Issue by Allroha** [xzsk2/TG-EFB-QQ-Docker#30]
我现在换了ARM 这个报错是架构问题吗🤔

**Comment by sakarie9** [comment]
大概是gocqhttp的架构不对，下一个arm64的二进制手动配置运行吧

**Comment by sakarie9** [comment]
https://github.com/xzsk2/EFB-Docker/commit/12153fd448d8edb44f7db5868724e45fcedafa7b
https://github.com/xzsk2/Go-CQHTTP-Docker/commit/c683053719b8482c166a50aa41f1136fd3717cf4

已添加 arm64 支持
