### ISSUE TITLE
QQ禁止异地扫码登录

### ISSUE THREAD

**Issue by maakoshiro** [xzsk2/TG-EFB-QQ-Docker#31]
如题，如何开启滑动验证登录

**Comment by sakarie9** [comment]
滑动登陆的实现方式比较复杂，参考 [滑块验证码](https://docs.go-cqhttp.org/faq/slider.html)，可以尝试下面几种方法

- 直接在 `config.yml` 里输入密码
- 修改 `device.json` 中的登陆协议 [设备信息](https://docs.go-cqhttp.org/guide/config.html#%E8%AE%BE%E5%A4%87%E4%BF%A1%E6%81%AF)
- 在常用QQ的本地网络环境中部署 go-cqhttp ，成功登陆后把 `device.json` 复制到云服务器上
