### ISSUE TITLE
执行自动更新报错，如下

### ISSUE THREAD

**Issue by Arturia169** [xzsk2/TG-EFB-QQ-Docker#33]
![image](https://user-images.githubusercontent.com/69199123/185289334-fc817946-32a1-4aa5-a726-819a988ab89f.png)

**Comment by Arturia169** [comment]
尝试使用指令停止该容器发生以下报错
![image](https://user-images.githubusercontent.com/69199123/185292073-46a85ce3-8594-4d48-adc6-1d7caab44911.png)

**Comment by sakarie9** [comment]
`docker container stop watchtower`
`docker container rm watchtower`

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/185292492-835fca68-6e00-4ec4-a4e9-ff883d5d469b.png)
感谢已解决

**Comment by Arturia169** [comment]
![image](https://user-images.githubusercontent.com/69199123/185293030-179fd9c7-5ed7-44a5-a661-10d3e6d5dc6c.png)
一直有个更新，貌似没有自动更新成功

**Comment by sakarie9** [comment]
#20

**Comment by Arturia169** [comment]
🆗
