### ISSUE TITLE
怎么手动更新镜像中的go cqhttp到指定版本

### ISSUE THREAD

**Issue by dongyu66** [xzsk2/TG-EFB-QQ-Docker#35]
当前版本无法使用mac接口登陆,dev版本适配了最新的mac登陆接口

**Comment by sakarie9** [comment]
暂时先换一个登陆协议？等 gocq 发了 release 这边才能跟着更新

或者不用 docker，自己编译运行 dev 的 gocq 应该也可以

**Comment by sakarie9** [comment]
已经更新到了 rc4，拉一下新版本镜像就好
