### ISSUE TITLE
go-cqhttp 分支的文件发送不支持

### ISSUE THREAD

**Issue by StephenSSR** [xzsk2/TG-EFB-QQ-Docker#7]
请问go-cqhttp 分支是不是没有默认打开文件的发送功能呢，还是bug？文件可以接受，语音确实可以发送，但还是不能发送文件，bot提示从端qq slave不支持file消息，配置部分只修改了``blueset.telegram/config.yaml ``内的 ``token ``及 ``admins``、``gocq/config.yml ``配置文件中的账号，``gocq/device.json``中改为了mac登录

**Comment by sakarie9** [comment]
又测试了一下确实不能发送文件，需要等qq-slave实现
