### ISSUE TITLE
如何过滤加群退群消息？

### ISSUE THREAD

**Issue by CHN-beta** [xzsk2/TG-EFB-QQ-Docker#8]
go-cqhttp 似乎是支持[按照文本内容过滤消息](https://docs.go-cqhttp.org/guide/eventfilter.html)的，但我不确定我理解的对不对。

如果确实可以按照上述文档过滤消息的话，文档中所述的 json 应该放到哪里呢，以及同时需要修改哪些配置文件呢？

**Comment by sakarie9** [comment]
1. 编辑gocq/config.yml，修改filter目录
```
default-middlewares: &default
  access-token: ''
  # 事件过滤器文件目录
  filter: '/data/filter.json' #修改这里
```

2. 新建gocq/filter.json，写入以下内容

<details>
<summary>无效配置，用楼下的</summary>

```
{
    "notice_type": {
        ".or": [
            {
                ".neq": "group_increase"
            },
            {
                ".neq": "group_decrease"
            }
        ]
    }
}
```

</details>


大概就可以了，如果有问题可以参考 [事件 - 群成员减少](https://docs.go-cqhttp.org/event/#%E7%BE%A4%E6%88%90%E5%91%98%E5%87%8F%E5%B0%91) 修改filter.json

**Comment by gaxdel** [comment]
> 

这个规则不能过滤加群退群消息。改成下面这个规则就可以了。
```
{
    ".not": {
        ".or": [
            {
                "notice_type": "group_decrease"
            },
            {
                "notice_type": "group_increase"
            }
        ]
    }
}

**Comment by sakarie9** [comment]
> > 
> 
> 这个规则不能过滤加群退群消息。改成下面这个规则就可以了。
> 
> ```
> {
>     ".not": {
>         ".or": [
>             {
>                 "notice_type": "group_decrease"
>             },
>             {
>                 "notice_type": "group_increase"
>             }
>         ]
>     }
> }
> ```

确认有效
