### ISSUE TITLE
 go-cqhttp已更新v1.0.0-beta5，求更新

### ISSUE THREAD

**Issue by StephenSSR** [xzsk2/TG-EFB-QQ-Docker#9]
go-cqhttp已更新v1.0.0-beta5，但该项目下载的还是beta4，求作者更新

**Comment by sakarie9** [comment]
已经是beta5了，重新 `docker pull xzsk2/gocqhttp-docker:latest` 一下

或者使用 [watchtower](https://github.com/containrrr/watchtower) 更新
```
docker run --rm \
    -v /var/run/docker.sock:/var/run/docker.sock \
    containrrr/watchtower -c \
    --run-once
```

**Comment by StephenSSR** [comment]
好了好了，多谢大佬
